### ISSUE TITLE
Question regarding setting up MoCha on Google Cloud

### ISSUE THREAD

**Issue by xuj18** [freeseek/mocha#10]
Hi Giulio,
    Thanks for this well documented WDL pipeline! I am trying to set up my Google VM to run MoCha. And I followed your suggestions up to the step for starting the Cromwell server on the Google VM: "(java -Xmx3500m -Dconfig.file=PAPIv2.conf -jar cromwell-58.jar server &)". However, I got the error message as below -

 Google Pipelines API configuration is not valid: Errors:
`google` configuration stanza does not contain an auth named '123456789876-compute@developer.gserviceaccount.com'.  Known auth names: application-default
`google` configuration stanza does not contain an auth named '123456789876-compute@developer.gserviceaccount.com'.  Known auth names: application-default

Do you know how I can fix this?

Thanks!
Jiayi

**Comment by freeseek** [comment]
After you included the stanza:
```
google {
  application-name = "cromwell"
  auths = [
    {
      name = "service-account"
      scheme = "service_account"
      json-file = "{google-project}.key.json"
    }
  ]
}
```
You have to change *both* `auth = "application-default"` occurrences to `auth = "service-account"`.

I am not sure what your error means but it would be much more effective for me to provide help if I could see how you have actually edited the `PAPIv2.conf` file. Unfortunately this is a tedious technical step that has to be endured if you want to run your own Cromwell server.

**Comment by xuj18** [comment]
Hi Giulio,
    Yes I changed the name, scheme, and two places for auth to the specific service account. Please see attached for my PAPIv2.conf file. Thanks so much for your help!

Best,
Jiayi
________________________________
