### ISSUE TITLE
Working with BAM files

### ISSUE THREAD

**Issue by fmpds** [freeseek/mocha#14]
Hello, how are you?

I am trying to use MoChA to identify somatic mosaicism in BAM files. I would like suggestions on how I can convert the BAM files to VCF so that I can use MoChA. I have tried using the command:

samtools mpileup -uf GCA_000001405.15_GRCh38_no_alt_analysis_set.fna myfilename.bam | bcftools call -mv  > var.raw.vcf

But when I run the following code:

bcftools +mocha -g GRCh38 -o output.bcf -Ob -c calls.tsv -z stats.tsv var.raw.vcf

I get the following error:

Failed to open /path/to/fie/var.raw.vcf: not compressed with bgzip

So I used bgzip to compress the file, with the following command:

bgzip < var.raw.vcf > var.raw.vcf.gz

and I ran the command again, and it returned the following error:

Error: input VCF file must contain either the AD format field or the BAF and LRR format fields

I would like help in finding the best way to process the bam files. 

Cheers, Felipe.

**Comment by freeseek** [comment]
Yes, the VCF needs to have an AD format field, that is, it must contain read counts at heterozygous sites, otherwise you cannot run the model. There should be a way to include that information with bcftools. However, do notice that you cannot run the MoChA model that way. The genotypes need to be phased, or otherwise you will only run the unphased model which is not powered to identify mosaic events. Furthermore, while MoChA can be run on high coverage WGS data (and in practice only that kind of NGS data), it will generate an endless stream of false positives if you don't perform a significant amount of quality control, as the model assumes that at each wild type heterozygous site you expect the same number of reference and alternate alleles.

**Comment by fmpds** [comment]
Thank you very much for the information. I started to do the phased step, however I got the following error with +scatter :

The bcftools plugin "scatter" was not found or is not functional in
	BCFTOOLS_PLUGINS="/path/to/bin".

The command I ran was as follows:

bcftools isec --no-version -Or --complement --exclude "N_ALT>1" --write 1 $dir/$pfx.unphased.bcf $dir/$pfx.xcl.bcf | \
> bcftools annotate --no-version -Or --remove ID,QUAL,INFO,^FMT/GT | | \
> bcftools +scatter --no-version -Ob --output $dir --scatter $(echo chr{{1..22},X} | tr ' ',') --prefix $pfx.

I have reached the folder and it really isn't there. Does this plugin need to be installed separately? Do you know where I can download it?

Cheers

**Comment by freeseek** [comment]
You will need BCFtools 1.13 or newer to access the +scatter plugin. Alternatively, you can split a VCF across chromosomes with a for loop. Other than that, BCFtools 1.11 should be sufficient. I would not use versions older than 1.11 though.

**Comment by fmpds** [comment]
Hello, how are you?

I'm new in bioinformatics and I'm having some difficulties to use the tool. I followed the scripts provided on the github page to perform the phasing, concatenate the files and proceed to the pipeline for calling chromosomal changes, but I'm not getting a clear understanding of what input files I should provide.

Here are the commands used:

Phasing:
for chr in {1..22} X; do
  bcftools index --force $dir/$pfx.chr$chr.bcf
  zcat $map | sed 's/^23/X/' | awk -v chr=$chr '$1==chr {print $2,$3,$4}' > $dir/genetic_map.chr$chr.txt
  shapeit4 \
    --thread $thr \
    --input $dir/$pfx.chr$chr.bcf \
    --reference $panel_pfx${chr}$panel_sfx.bcf
    --map $dir/genetic_map.chr$chr.txt
    --region chr$chr
    --output $dir/$pfx.chr$chr.pgt.bcf
done

Concatanate
bcftools concat --no-version -Ob $dir/$pfx.chr{{1..22},X}.pgt.bcf | \
  tee $dir/$pfx.pgt.bcf | | \
  bcftools index --force --output $dir/$pfx.pgt.bcf.csi

Call mosaic chromosomal alterations:

bcftools +mocha \
  --genome $assembly
  --input-stats $tsv
  --no-version
  --output-type b
  --variants ^$dir/$pfx.xcl.bcf
  ---calls $dir/$pfx.calls.tsv
  --stats $dir/$pfx.stats.tsv
  --ucsc-bed $dir/$pfx.ucsc.bed
  --cnp $cnp
  --mhc $mhc_reg
  --kir $kir_reg
  $dir/$pfx.bcf
  tee $dir/$pfx.as.bcf | \
  bcftools index --force --output $dir/$pfx.as.bcf.csi

I don't understand what the input file is (in this case, the last file I have is $pfx.pgt.bcf from the previous step, but as I understand it, the input here would be $pfx.bcf). Am I missing a step? 

Cheers,
Felipe.

**Comment by freeseek** [comment]
You are almost there. There is step where you import the phased genotypes that is missing:
```
bcftools annotate --no-version -Ob --annotations $dir/$pfx.pgt.bcf --columns -FMT/GT $dir/$pfx.unphased.bcf | \
  tee $dir/$pfx.bcf | \
  bcftools index --force --output $dir/$pfx.bcf.csi
```
The meaning of the suffixes is that `.pgt` stands for phased genotypes, that is the VCF only contains the GT FORMAT field and the genotypes are phased. This information needs to be imported in the VCF with the probe intensities (BAF and LRR) and the resulting VCF is what MoChA takes as input. Let me know if this still does not work.

**Comment by fmpds** [comment]
It worked! I really appreciate your help! Usually it is difficult to get in touch with the developers, but you are always active and helping, thank you very much!

Cheers.

**Comment by fmpds** [comment]
Hello, how are you?

I have some questions regarding the HMM models used by MoCHa. Where can I find more information on how they work?
What about the filter for non-germinating events:

awk -F "\t" 'NR==1 {for (i=1; i<=NF; i++) f[$i] = i; print}
  NR>1 {len=$(f["length"]); bdev=$(f["bdev"]); rel_cov=$(f["rel_cov"])}
  NR>1 && $(f["type"])!~"^CNP" &&
  ( $(f["chrom"])~"X" && $(f["computed_gender"])=="M" || bdev<0.1 || $(f["n50_hets"])<2e5 ) &&
  ( $(f["bdev_se"])!="nan" || $(f["lod_baf_phase"])!="nan" && $(f["lod_baf_phase"]) > 10.0 ) &&
  ( rel_cov<2.1 || bdev<0.05 || len>5e5 && bdev<0.1 && rel_cov<2.5 || len>5e6 && bdev<0.15 )' \
  $pfx.calls.tsv > $pfx.mca.calls.tsv

Where can I find a more detailed explanation of its operation and parameters?

Thank you very much.
Cheers.

**Comment by freeseek** [comment]
For now the best references are the supplementary material in the [2018](http://doi.org/10.1038/s41586-018-0321-x) paper and the section [here](https://github.com/freeseek/mocha/#hmm-parameters). Do notice that MoChA was not used in the paper, but the model is fairly similar. Unfortunately there is no published paper about how MoChA works for now. I plan to have one at some point but this is not top priority for now as some parts are still a work in progress. For the filters, the best explanation is [here](https://github.com/freeseek/mocha/#filter-callset). The filtering strategy is similar to what was done in the 2018 paper which again is the best reference.

**Comment by fmpds** [comment]
Hello, how are you?

I am trying to use summary_plot.R, but the graphs have no values.. Do you know what is happening? My statistics and call table are not null. When I run the command:

```
summary_plot.R \ 
  --stats $dir/$pfx.stats.tsv \
  - calls $dir/$pfx.calls.tsv \
  --pdf $dir/$pfx.pdf
```

the following warnings are displayed:

**Warning message:
The transformation entered infinite values on the continuous x-axis 
Warning message:
Removed 5 rows containing non-finite values (stat_bin).**

Do you think this might be the problem? 

Translated with www.DeepL.com/Translator (free version)

**Comment by fmpds** [comment]
Hello, how are you?

I have another question about the plots. When i run the following command:
'''
bcftools +mocha \
  --genome $assembly \
  --input-stats $tsv \
  --no-version \
  --output-type b \
  --variants ^$dir/$pfx.xcl.bcf \
  --calls $dir/$pfx.calls.tsv \
  --stats $dir/$pfx.stats.tsv \
  $dir/$pfx.bcf | \
  tee $dir/$pfx.as.bcf | \
  bcftools index --force --output $dir/$pfx.as.bcf.csi
'''

my $pfx.as.bcf file is empty. i don't understand whats happening.

**Comment by freeseek** [comment]
For the R issue, it  is difficult to understand what is going on, as R gives awful error messages without providing the line that caused the issue. I could look into it if you could share the input files you used. For the MoChA issue, the file should not be empty. What was the output of the MoChA command?

**Comment by freeseek** [comment]
You are right, there is an error in the command line I provided. It should be as follows:
```
bcftools +mocha \
  --genome $assembly \
  --input-stats $tsv \
  --no-version \
  --output - \
  --output-type b \
  --variants ^$dir/$pfx.xcl.bcf \
  --calls $dir/$pfx.calls.tsv \
  --stats $dir/$pfx.stats.tsv \
  $dir/$pfx.bcf | \
  tee $dir/$pfx.as.bcf | \
  bcftools index --force --output $dir/$pfx.as.bcf.csi
```

**Comment by fmpds** [comment]
What does the '-' mean ? I ran the command you shared and got the following errors:

[E::hts_open_format] Failed to open file "--no-version" : No file or directory of this type
Could not open ---no version: No such file or directory
[T::bgzf_read_block] The EOF marker is missing. The entry may be truncated
[E::bcf_hdr_read] Failed to read BCF header
index: failed to create index for "-"

**Comment by fmpds** [comment]
Thanks, it worked here! I'll try to generate the graphs now!

Cheers

**Comment by fmpds** [comment]
Giulio, when i run this command:

mocha_plot.R \
  --wgs \
  --mocha \
  --stats ./results.stats.tsv
  --vcf ./results.as.bcf \
  --png teste.png \
  --samples 002-001-033 \
  --regions 1:16048038-16946901 \
  --cytoband ./cytoBand.txt.gz
  
i have the following error message:

Error: option --vcf is required
Execution halted
bash: --vcf: command not found

I have that convert the bcf file to vcf file?

**Comment by freeseek** [comment]
No you don't need to convert the BCF to VCF. I am going to guess that the issue is the lack of `\` at the end of each line and that you actually run the `mocha_plot.R` command without any options, that is, you should run like this:
```
mocha_plot.R \
  --wgs \
  --mocha \
  --stats ./results.stats.tsv \
  --vcf ./results.as.bcf \
  --png teste.png \
  --samples 002-001-033 \
  --regions 1:16048038-16946901 \
  --cytoband ./cytoBand.txt.gz
```

**Comment by fmpds** [comment]
Thanks, but it hasn't worked yet. After the fix, I got the following error: 

Command: bcftools query --format "[%CHROM\t%POS\t%REF\t%ALT\t%SAMPLE\t%GT\t%AD{0}\t%AD{1}\t%Ldev\t%Bdev\n]" results.as.bcf --samples 002-001-033 --regions 1:15598606-17396332
Error in names(object) <- nm : 
  'names' attribute [10] must be the same length as the vector [0]
Calls: setNames

**Comment by freeseek** [comment]
What happens if you run corresponding `bcftools query` command? Are you sure you should not be using `--regions chr1:15598606-17396332` instead?

**Comment by fmpds** [comment]
I don't understand. If i run the bcftools query separetely? I ran separetely but it didn't return anything and didn't create any documents. I run with  --regions chr1:15598606-17396332, but i have the same error message. I not putting it in the previuos message, but the error comes with a warning message:

In addition: Warning message:
In fread(cmd = cmd, sep = "\t", header = FALSE, na.strings = ".",  :
  File '/tmp/Rtmpj01TDd/file352594ee46' has size 0. Returning a NULL data.frame.
Execution halted
