### ISSUE TITLE
Question about call rate

### ISSUE THREAD

**Issue by yifnzhao** [freeseek/mocha#17]
Hi, 

I am working with WGS data, and I am wondering how the call rate should be determined. Thanks in advance for your help!

Best regards,
Yifan

**Comment by freeseek** [comment]
For the MoChA WDL pipeline, you can leave the call rate for WGS data as `1.0` if your VCF does not include `./.` calls. In the future versions of the pipeline I will remove the need for that column in the case of WGS data.

**Comment by yifnzhao** [comment]
Thank you!
