### ISSUE TITLE
Problem with chr X XTR and Non_par regions

### ISSUE THREAD

**Issue by Emmanuel-CEPH** [freeseek/mocha#19]
Dear Sir,

after preparing files and preprocessing my VCF file (GC content, phasing, etc...) , I'm trying to run bcftools +mocha and I encounter the following error :

WARNING: bcftools version mismatch .. bcftools at 1.14, the plugin "mocha" at 1.11
MoChA 2021-10-15 https://github.com/freeseek/mocha
Genome reference: GRCh37
Variants to exclude:NG.xcl.bcf
Regions to genotype: /mocha/grch37/cnps.bed
Genome-wide statistics: ng.stats
MHC region to exclude from analysis: 6:27486711-33448264
KIR region to exclude from analysis: 19:54574747-55504099
BAF deviations for LRR+BAF model: -2.0,-4.0,-6.0,10.0,6.0,4.0
BAF deviations for BAF+phase model: 6.0,8.0,10.0,15.0,20.0,30.0,50.0,80.0,100.0,150.0,200.0
Minimum base pair distance between consecutive sites: 400
Order of polynomial in local GC content to be used to regress LRR against GC: 2
Major transition phred-scaled likelihood: 65.00
Minor transition phred-scaled likelihood: 35.00
Autosomal telomeres phred-scaled likelihood: 20.00
Chromosome X telomeres phred-scaled likelihood: 8.00
Chromosome Y telomeres phred-scaled likelihood: 6.00
Uniform error phred-scaled likelihood: 15.00
Phase flip phred-scaled likelihood: 20.00
List of short arms: 13,14,15,21,22,chr13,chr14,chr15,chr21,chr22
Use variants in short arms: FALSE
Use variants in centromeres: FALSE
Use chromosomes without centromere rules: FALSE
Relative contribution from LRR for LRR+BAF model: 0.20
Difference between LRR for haploid and diploid: 0.69
**Chromosome X XTR and nonPAR regions declared on different contigs: chrX:2699520-154930289    X_nonpar**

Surely a mismatch in references preparation but I don't know where to look to fix this.

Many thanks for your help and an happy new year.

Regards.

Emmanuel

My command is 
bcftools +mocha \
  --genome $assembly \
  --input-stats $tsv \
  --no-version \
  --output - \
  --output-type b \
  --variants ^$dir/$pfx.xcl.bcf \
  --calls $dir/$pfx.calls.tsv \
  --stats $dir/$pfx.stats.tsv \
  --ucsc-bed $dir/$pfx.ucsc.bed \
  --cnp $cnp \
  --mhc $mhc_reg \
  --kir $kir_reg \
  $dir/$pfx.bcf | \
  tee $dir/$pfx.as.bcf | \
  bcftools index --force --output $dir/$pfx.as.bcf.csi

**Comment by freeseek** [comment]
This is puzzling. I am trying to replicate this issue on my side. Can you show me the output of:
```
$ bcftools view -h $dir/$pfx.bcf | grep ^##contig 
```
I am guessing that maybe you have both `X` and `chrX` in your VCF, which would be very odd.

**Comment by Emmanuel-CEPH** [comment]
Thank you for your support, here is the output of the bctools command :

##contig=<ID=chr1,length=249250621>
##contig=<ID=chr2,length=243199373>
##contig=<ID=chr3,length=198022430>
##contig=<ID=chr4,length=191154276>
##contig=<ID=chr5,length=180915260>
##contig=<ID=chr6,length=171115067>
##contig=<ID=chr7,length=159138663>
##contig=<ID=chr8,length=146364022>
##contig=<ID=chr9,length=141213431>
##contig=<ID=chr10,length=135534747>
##contig=<ID=chr11,length=135006516>
##contig=<ID=chr12,length=133851895>
##contig=<ID=chr13,length=115169878>
##contig=<ID=chr14,length=107349540>
##contig=<ID=chr15,length=102531392>
##contig=<ID=chr16,length=90354753>
##contig=<ID=chr17,length=81195210>
##contig=<ID=chr18,length=78077248>
##contig=<ID=chr19,length=59128983>
##contig=<ID=chr20,length=63025520>
##contig=<ID=chr21,length=48129895>
##contig=<ID=chr22,length=51304566>
##contig=<ID=chrX,length=155270560>
##contig=<ID=chrY,length=59373566>
##contig=<ID=chrMT,length=16569>
##contig=<ID=GL000207.1,length=4262>
##contig=<ID=GL000226.1,length=15008>
##contig=<ID=GL000229.1,length=19913>
##contig=<ID=GL000231.1,length=27386>
##contig=<ID=GL000210.1,length=27682>
##contig=<ID=GL000239.1,length=33824>
##contig=<ID=GL000235.1,length=34474>
##contig=<ID=GL000201.1,length=36148>
##contig=<ID=GL000247.1,length=36422>
##contig=<ID=GL000245.1,length=36651>
##contig=<ID=GL000197.1,length=37175>
##contig=<ID=GL000203.1,length=37498>
##contig=<ID=GL000246.1,length=38154>
##contig=<ID=GL000249.1,length=38502>
##contig=<ID=GL000196.1,length=38914>
##contig=<ID=GL000248.1,length=39786>
##contig=<ID=GL000244.1,length=39929>
##contig=<ID=GL000238.1,length=39939>
##contig=<ID=GL000202.1,length=40103>
##contig=<ID=GL000234.1,length=40531>
##contig=<ID=GL000232.1,length=40652>
##contig=<ID=GL000206.1,length=41001>
##contig=<ID=GL000240.1,length=41933>
##contig=<ID=GL000236.1,length=41934>
##contig=<ID=GL000241.1,length=42152>
##contig=<ID=GL000243.1,length=43341>
##contig=<ID=GL000242.1,length=43523>
##contig=<ID=GL000230.1,length=43691>
##contig=<ID=GL000237.1,length=45867>
##contig=<ID=GL000233.1,length=45941>
##contig=<ID=GL000204.1,length=81310>
##contig=<ID=GL000198.1,length=90085>
##contig=<ID=GL000208.1,length=92689>
##contig=<ID=GL000191.1,length=106433>
##contig=<ID=GL000227.1,length=128374>
##contig=<ID=GL000228.1,length=129120>
##contig=<ID=GL000214.1,length=137718>
##contig=<ID=GL000221.1,length=155397>
##contig=<ID=GL000209.1,length=159169>
##contig=<ID=GL000218.1,length=161147>
##contig=<ID=GL000220.1,length=161802>
##contig=<ID=GL000213.1,length=164239>
##contig=<ID=GL000211.1,length=166566>
##contig=<ID=GL000199.1,length=169874>
##contig=<ID=GL000217.1,length=172149>
##contig=<ID=GL000216.1,length=172294>
##contig=<ID=GL000215.1,length=172545>
##contig=<ID=GL000205.1,length=174588>
##contig=<ID=GL000219.1,length=179198>
##contig=<ID=GL000224.1,length=179693>
##contig=<ID=GL000223.1,length=180455>
##contig=<ID=GL000195.1,length=182896>
##contig=<ID=GL000212.1,length=186858>
##contig=<ID=GL000222.1,length=186861>
##contig=<ID=GL000200.1,length=187035>
##contig=<ID=GL000193.1,length=189789>
##contig=<ID=GL000194.1,length=191469>
##contig=<ID=GL000225.1,length=211173>
##contig=<ID=GL000192.1,length=547496>
##contig=<ID=NC_007605,length=171823>
##contig=<ID=hs37d5,length=35477943>
##contig=<ID=1>
##contig=<ID=2>
##contig=<ID=3>
##contig=<ID=4>
##contig=<ID=5>
##contig=<ID=6>
##contig=<ID=7>
##contig=<ID=8>
##contig=<ID=9>
##contig=<ID=10>
##contig=<ID=11>
##contig=<ID=12>
##contig=<ID=13>
##contig=<ID=14>
##contig=<ID=15>
##contig=<ID=16>
##contig=<ID=17>
##contig=<ID=18>
##contig=<ID=19>
##contig=<ID=20>
##contig=<ID=21>
##contig=<ID=22>
##contig=<ID=X>
##contig=<ID=Y>
##contig=<ID=MT>

**Comment by freeseek** [comment]
Yeah, so what is going on is that the code assigns XTR to `X` and then nonPAR to `chrX` and there is a sanity check that alerts something is off. It is a good thing that you are getting an error, though likely not the error message you would have wanted. How did you end up with a VCF with both `X` and `chrX`? You seem to have some more serious issues in the pipeline that generated the input VCF.

**Comment by Emmanuel-CEPH** [comment]
My original vcf header does not contain the last part of contig lines (those ##contig=<ID=16>) only the first one <ID=chrNN>.

At some point I msut have changed from chrN to N to agree with the refrence.
Damn, century 21 it looks like and we still don't have a  normalized chromosome naming...
Should I just replace the original chrN in my header and remove the additional contig lines ??

Thanks.

**Comment by freeseek** [comment]
You should not have both contig names, that for sure. You should have the contig names in the header that match the contig names used for the variants. MoChA is designed to be flexible, so you can use either the names with or without the `chr` prefix. But not both.

**Comment by Emmanuel-CEPH** [comment]
Hi,

finally it works, I had to remove the ##contig=<ID=XXX> entries and rename entries like 
##contig=<ID=chr1,length=249250621> into ##contig=<ID=1,length=249250621> to match vcf records coordinates.

For now, I am runnnig MoCha without --input-stats, is it possible to find an example file or how to generate one ?
My only input file is a vcf from whole genome sequencing.

Anyway, thank you again for your support.
