### ISSUE TITLE
1.15?

### ISSUE THREAD

**Issue by outpaddling** [freeseek/mocha#23]
bcftools 1.15 has been released.  Are you planning a corresponding release for MoCha, or is 1.14 compatible with bcftools 1.15?

**Comment by freeseek** [comment]
It is okay to use the 1.14-20220112 version of MoChA with BCFtools and HTSlib 1.15 and now that 1.15 is out, it is appropriate to do so due to the [bug](https://github.com/samtools/htslib/issues/1362) affecting HTSlib 1.14 which causes MoChA to fail to generate an output VCF

**Comment by outpaddling** [comment]
Great, thanks.
