### ISSUE TITLE
question with call cnv for array data

### ISSUE THREAD

**Issue by lizhan96** [freeseek/mocha#27]
hi there,

I have successfully run the phase pipeline.

but it's seem that the Chromosomal alterations pipeline guileline was only described for the WGS data but not array data? Could you send me some example as reference.

**Comment by lizhan96** [comment]
Dose the batch file is required? I don't have such file.

**Comment by lizhan96** [comment]
So could you give me reference code for using MoChA with array data?

I can't find that in the link https://github.com/freeseek/mocha/tree/master/wdl#illumina-example you gave me

**Comment by freeseek** [comment]
The instructions provided related to [data preparation](https://github.com/freeseek/mocha#data-preparation) explain to great depth how to input array data.

**Comment by lizhan96** [comment]
`bcftools +mocha \
  --genome $assembly \
  --input-stats $tsv \
  --no-version \
  --output - \
  --output-type b \
  --variants ^$dir/$pfx.xcl.bcf \
  --calls $dir/$pfx.calls.tsv \
  --stats $dir/$pfx.stats.tsv \
  --ucsc-bed $dir/$pfx.ucsc.bed \
  --cnp $cnp \
  --mhc $mhc_reg \
  --kir $kir_reg \
  $dir/$pfx.bcf | \
  tee $dir/$pfx.as.bcf | \
  bcftools index --force --output $dir/$pfx.as.bcf.csi`

for this code, which paramnent is required with array data in calling CNV?

**Comment by freeseek** [comment]
I do not understand what you are asking. Each parameter is optional and has an equal effect whether you run MoChA on array data or WGS data.

**Comment by lizhan96** [comment]
got it.

I have solved the problem. Thanks for your help!
