### ISSUE TITLE
question about calling CNV with tumor and normal-pair sample

### ISSUE THREAD

**Issue by lizhan96** [freeseek/mocha#28]
Dear developer

I want to call CNV with my tumor sample(array data), and the normal-pair sample i had.

When I run the MoChA pipeline, some hg19/hg39 related files was needed.

Should I use the nomal sample related files as the input instead of that hg19/hg39 related files? Could you tell me which files I should change?

Thank you!

**Comment by freeseek** [comment]
MoChA does not have a framework to compare normal and tumor data. You can analyze the two together, but they will be called as separate samples. The GRCh37/GRCh38 resources are needed for other aspects of the analyses such as phasing and knowledge of the location of common copy number polymorphisms.

**Comment by freeseek** [comment]
I am not sure what I would suggest you beyond what is already in the documentation.
