### ISSUE TITLE
query about calling CNV with multi-samples

### ISSUE THREAD

**Issue by Xxhongs** [freeseek/mocha#29]
Dear developer

I want to call CNV among multi-samples.

So when i run mocha, is there any difference for the output CNV results between inputting samples one by one or merging these samples?

Thank you!

**Comment by freeseek** [comment]
When running MoChA on sequence data, it does not matter whether you run one sample or multiple samples at once. When you run MoChA on array data, there are several adjustments performed to normalize the BAF that benefit from running multiple samples together, as long as those samples are homogeneous (e.g. they were part of the same batch). However, do notice that phasing always benefits from running samples from multiple individuals at once.
