### ISSUE TITLE
check bpm or not 

### ISSUE THREAD

**Issue by psytky03** [freeseek/mocha#31]
Hi, Giulio, I have a question regarding the `"mocha.do_not_check_bpm": true` in the MoCha configuration. 
Should I change it to false if I use a more recent Illumina array, say Infinium Global Screening Array?  
It will be great if you can share some insights into the logic behind this parameter.

Thanks

**Comment by freeseek** [comment]
You can just remove that option (it will default to false). It is only needed for very old arrays such as the Illumina HumanCNV370v1.

**Comment by psytky03** [comment]
Thanks. I will remove this line.
