### ISSUE TITLE
GC content in VCF file

### ISSUE THREAD

**Issue by AkshajD** [freeseek/mocha#35]
Forgive me for the naïve question, but I am new to genetic analysis and struggling with one of the requirements of this pipeline.

I have WGS data in BAM formats that I am currently running through GATK's HaplotypeCaller in order to get the VCF file. However, upon inspection of this file, while I have all the other requirements, I don't seem to have the GC content.

I have tried searching it up online but wasn't able to find any information on this.
As I understand, the original, unphased VCF file that runs through the remainder of your tutorial should have this information, so do you have any recommendations?

**Comment by freeseek** [comment]
You can add the `INFO/GC` field with the command
```
bcftools +mochatools --no-version -Ob $vcf -- -t GC -f $ref
```

**Comment by AkshajD** [comment]
Perfect, that worked!
