### ISSUE TITLE
Any suggestions on filters for downstream analysis?

### ISSUE THREAD

**Issue by dessytat** [freeseek/mocha#37]
Hi! Below are a few reflections on the different filters used to identify mLOY, mLOX and autosomal mCAs in the tool.  

1. We generated the phenotype files from the filtered MoChA calls.
2. #33 clarifies that mLOY and mLOX event counts obtained using LRR classification would differ from counts obtained from filters used to generate the `pheno.filtered.tsv` file  (`f["computed_gender"])=="M" && $(f["chrom"])~"X" && $(f["length"])>2e6 && $(f["rel_cov"])<2.5`) because using classification by LRR (`type` column) would not be reliable for chromosomes X and Y. However, we found 36.8% mLOY events in the male subset of our data based on filters applied to `calls.filters.tsv` which is substantially larger than what we identified for mLOY in males from the European-ancestry subset of the UK Biobank (12.6%). 
3. Autosomal mCA event counts are substantially different when using LRR classification (`mca.calls.filtered.tsv`) compared to filters used to generate the `pheno.filtered.tsv` file .    

Isn’t LRR supposed to be reliable enough for chromosomes 1:22? Which filter would you recommend for downstream analysis? Thanks for your help, I'm happy to clarify any points if needed.

**Comment by freeseek** [comment]
My rate of mLOY events in males from the UKB when the array data is processed with MoChA following the instructions [here](https://github.com/freeseek/mochawdl/blob/master/ukb2txt.md) is 20.4%. As for the autosomal mCAs, you often need to use LRR to classify the events and very low cell fraction events cannot be classified as a result. You can be more aggressive in your classification if you are willing to allow some false positives. For mLOX and mLOY is acceptable to be more aggressive as the prior that large events are losses is very high. While LRR on the autosomes might be more reliable than on chromosome X (how reliable is cohort specific), it is still the case that it is not reliable for low cell fraction events and so many of those events are often left classified with undetermined type

**Comment by dessytat** [comment]
This was very helpful. Thank you for your quick response!
