### ISSUE TITLE
Imputation Error - terminate called after throwing an instance of std::length_error

### ISSUE THREAD

**Issue by AkshajD** [freeseek/mocha#38]
I am running the phasing pipeline on a VCF of 5 samples and running into some errors with the imputation step for chromosomes 1-4.

The imputation output for chromosome 1 is here:
```
Recombination rates given by genetic map
________________________________

Input read              [123.639s]
    Imputation region           [10177-249240543] [249.23Mb, 293.40cM]
    Markers     (ref/both/targ) [3740965/506109/0]
    Samples     (ref/targ)      [2504/5]
    Ploidy      (ref/targ)      [N_rd=2504, N_rh=0] [N_td=5, N_th=0]

    Buffer region               [10177-249240543] [249.23Mb, 293.40cM]
    Markers     (ref/both/targ) [3740965/506109/0]

________________________________

PBWT select             [10.89s]
    States      (avg/max)       [4817/4836]

ESC[33mWARNING: ESC[0mPossible performance decrease: one or more haplotypes have a large number of copying states [4836 > 2000].
While this could increase imputation accuracy, consider using smaller imputation regions to increase IMPUTE5 time/memory performances.
________________________________

  * HMM imputation [0%]^Mterminate called after throwing an instance of 'std::length_error'
  what():  vector::_M_default_append
/var/spool/slurmd/job6647381/slurm_script: line 88:  3635 Aborted                 (core dumped) impute5 --h $panel_pfx${chr}$panel_sfx.bcf --m $dir/genetic_map.chr$chr.txt --g $dir/$pfx.pgt.bcf --r $chr --o $dir/$pfx.chr$chr.imp.bcf --l $dir/$pfx.chr$chr.log --threads $thr
```

Firstly, it gives a warning about the fact that one of the haplotypes have a large number of copying states, which could lead to worse time/memory performances. Right now, this pipeline is burning through a lot of resources, so if you could suggest how I modify your code to tackle this warning and issue, it would be helpful.

But then, more importantly, as soon as the HMM imputation starts, it throws a `std::length_error`. Why might this error be taking place, and what can I do to fix it?

Thank you for your help.

**Comment by freeseek** [comment]
I am not sure as I am not the author of IMPUTE5. It might be that imputing the whole chromosome at once is too much for the software. I have a more complicated pipeline in [impute.wdl](https://github.com/freeseek/mochawdl) that will split in overlapping windows and then ligate the phased genotypes across the windows using the overlapping segments
