### ISSUE TITLE
Can't find file to patch at input line 3

### ISSUE THREAD

**Issue by vbruat** [freeseek/mocha#4]
Hi,

I've tried to run this command:
cd bcftools && patch < Makefile.patch && patch < main.patch && patch < vcfnorm.patch && cd ..

And I got this message:

can't find file to patch at input line 3
Perhaps you should have used the -p or --strip option?
The text leading up to this was:
--------------------------
|--- Makefile    2018-08-26 12:00:00.000000000 -0500
|+++ Makefile    2018-08-26 12:00:00.000000000 -0500
--------------------------
File to patch: 

Thanks.

**Comment by freeseek** [comment]
It means that in the directory where you are trying to run the patch command, the Makefile.patch file is present, but the Makefile file to update is not present. Maybe when you git-cloned bcftools something went wrong and it did not copy all the files(?). I am sorry the installation is a bit convoluted. In the long term this will be fixed.

**Comment by vbruat** [comment]
I re-started the installation from scratch and it works now. Thanks.
