### ISSUE TITLE
genetic map grch38

### ISSUE THREAD

**Issue by iranmdl** [freeseek/mocha#43]
Hi!

I just noticed that the genetic map has a numeric chromosome notation (1,2,3..X), while the reference panel files include the "chr" prefix. Does this have any effect?

Also, I have compared the genetic files provided by [shapeit5_resources](https://github.com/odelaneau/shapeit5/blob/main/resources/maps/b38/genetic_maps.b38.tar.gz) and the one provided by `mocha`, and there seem to be some differences, e.g:

```
grep -c ^21  genetic_map_hg38_withX.txt
42949

zcat chr21.b38.gmap.gz | wc -l
44619
```

Any guess of why this might be the case?

One last question, do `shapeit5` and `impute5` use the same genetic map?

Thank you in advance,

Irantzu

**Comment by freeseek** [comment]
At the moment, and for legacy reasons, I still advise to use the genetic map from Eagle2, which might be a little difference from the one used by SHAPEIT4 and SHAPEIT5. There is no good reason for this and you should feel free to use what you prefer. As long as you format it correctly, you can use the genetic map of your choice. I did not provide any input in the generation of the genetic maps
