### ISSUE TITLE
mocha on sequencing vcf

### ISSUE THREAD

**Issue by JenniferShelton** [freeseek/mocha#5]
Hi,
I have a question about input. Mocha is described as running off of VCFs with either:
phased genotypes (GT) and B-allele frequency (BAF) and Log R Ratio intensity (LRR)
or
phased genotypes (GT) and allelic depth coverage (AD) (for sequencing WGS)

When I run on a prepped BCF file with lines like the line below (the position below is only an example and may not match the ref base) :
chr1    817001  .       G       A       .       PASS    GC=0.50143;CpG=0.06392;AC_Het=1      GT:AD   0|1:18,20

I get this error 
`Error: input VCF missing the ALLELE_A info field.
Use bcftools +mochatools -- --infer-BAF-alleles to infer ALLELE_A`

when I run :
```
bcftools +mocha \
--rules $rule \
--no-version \
--output-type b \
--output ${dir}/${pfx}.mocha.bcf \
--threads $thr \
--variants ^${dir}/${pfx}.xcl.bcf \
--mosaic-calls ${dir}/${pfx}.mocha.tsv \
--genome-stats ${dir}/${pfx}.stats.tsv \
--ucsc-bed ${dir}/${pfx}.ucsc.bed \
--cnp ${cnp} \
 ${dir}/${pfx}.bcf
```

What is the cause of this message if the BCF file already includes the GT and AD?

Thanks

**Comment by freeseek** [comment]
It should be fixed now
