### ISSUE TITLE
HTTP request sent, awaiting response... 404 Not Found

### ISSUE THREAD

**Issue by MohdRashid01** [freeseek/mocha#6]
Hi All,

I got 404 not found in github below is the command
sudo wget -p  https://raw.githubusercontent.com/Repository01/Test/master/test.sh

My script is save in private repository when executed it got 404 not found  
Error
![image](https://user-images.githubusercontent.com/7812871/88478925-99f97680-cf69-11ea-98ad-5fb2fa6cb57d.png)

Please help me

**Comment by freeseek** [comment]
I have no idea where you got this command from:
```
sudo wget -p https://raw.githubusercontent.com/Repository01/Test/master/test.sh
```

**Comment by MohdRashid01** [comment]
@freeseek here is the screen shot
![image](https://user-images.githubusercontent.com/7812871/88509433-b398cd80-cffe-11ea-89ce-8fcad7e48345.png)

i have a script which upload on github i click on raw left side u see blame and edit and delete options are there.

**Comment by MohdRashid01** [comment]
@freeseek after few minutes i got 404 not found 
![image](https://user-images.githubusercontent.com/7812871/88510996-b517c500-d001-11ea-8b34-bd256edecd93.png)

**Comment by MohdRashid01** [comment]
> I have no idea where you got this command from:
> 
> ```
> sudo wget -p https://raw.githubusercontent.com/Repository01/Test/master/test.sh
> ```

Command is wrong correct one is
sudo wget https://raw.githubusercontent.com/MohdRashid01/Private/master/Private.sh

even with or without token its showing 404 not found see please above screenshot

**Comment by freeseek** [comment]
I think your issue is due to the fact that your repository is private so wget will not be able to see it as it does not make the download request using your credentials. But I really do not understand why you are asking this here in the MoChA issue page.
