### ISSUE TITLE
Missing GC info field

### ISSUE THREAD

**Issue by pukutanuki** [freeseek/mocha#7]
Hi All,

I am trying to run mocha, but I got the following error.

Error: input VCF has no GC info field: use "--LRR-GC-order 0/-1" to disable LRR adjustment through GC correction

I can find GC info in the $pfx.unphased.bcf, but not $pfx.bcf.... (after phasing by Eagle)

Could you help me?

**Comment by freeseek** [comment]
Eagle (at least the latest version) should not remove any INFO fields from you VCF. Alternatively, you can reintroduce the GC INFO field into the VCF using a command like the following:
```
bcftools +mochatools file.bcf -- --fasta-ref ref.fasta
```

**Comment by pukutanuki** [comment]
Thank you for your reply. I'll try the command.

 I found that GC info was lost when iI made $pfx.unphased.bcf from vcf file before Eagle.

I did the following command written In your tutorial, but I think GC info had gone after this command.

```
bcftools annotate --no-version -Ob -o $dir/$pfx.unphased.bcf $vcf \
  -x ID,QUAL,^INFO/ALLELE_A,^INFO/ALLELE_B,^FMT/GT,^FMT/BAF,^FMT/LRR && \
  bcftools index -f $dir/$pfx.unphased.bcf
```

**Comment by freeseek** [comment]
Ah good catch, thank you! I will have it fixed soon.
